# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='preData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=20)),
                ('longitude', models.CharField(max_length=20)),
                ('remark', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('img_url', models.TextField(max_length=30)),
                ('DateTimeCreated', models.DateTimeField(editable=False)),
                ('fbFriends', models.TextField(null=True)),
                ('isLocationTracking', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='predata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User'),
        ),
    ]
