# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-10 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNo', models.CharField(max_length=10)),
                ('carPlateNo', models.CharField(max_length=20)),
                ('carModel', models.CharField(max_length=20)),
                ('carMileage', models.CharField(max_length=20)),
                ('homeAdd', models.CharField(max_length=50)),
                ('officeAdd', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.User')),
            ],
        ),
    ]
