# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='test', max_length=10),
            preserve_default=False,
        ),
    ]
