# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fbFriends',
        ),
        migrations.AddField(
            model_name='user',
            name='isFBLogin',
            field=models.BooleanField(default='false'),
            preserve_default=False,
        ),
    ]
