# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20160612_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=20)),
                ('receiver', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=100)),
                ('DateTimeCreated', models.DateTimeField(editable=False)),
            ],
        ),
    ]
